services:
  postgres:
    image: postgres:17
    container_name: examconnect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - examconnect_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: examconnect-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - examconnect_redis_data:/data

volumes:
  examconnect_postgres_data:
  examconnect_redis_data: